import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import 'remixicon/fonts/remixicon.css';
import "./globals.scss";

export const montserrat = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["100","200","500","600","700","800"]
});

export const roboto = Roboto({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["100","300","400", "500", "700"]
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${roboto.className}`}>
        {children}
      </body>
    </html>
  );
}